from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Literal


class EdgeRelation(str, Enum):
    """Edge relationship types for C-stage classification."""
    SUPPORTS = "supports"
    CONTRADICTS = "contradicts"
    DEPENDS_ON = "depends_on"
    ELABORATES = "elaborates"
    UNRELATED = "unrelated"


# Relation multipliers for weighted graph construction
RELATION_MULTIPLIERS: dict[EdgeRelation, float] = {
    EdgeRelation.SUPPORTS: 1.0,
    EdgeRelation.CONTRADICTS: 0.8,
    EdgeRelation.DEPENDS_ON: 0.9,
    EdgeRelation.ELABORATES: 0.5,
    EdgeRelation.UNRELATED: 0.0,
}

# Structural relations (used for in_structural_weight)
STRUCTURAL_RELATIONS: set[EdgeRelation] = {
    EdgeRelation.SUPPORTS,
    EdgeRelation.DEPENDS_ON,
}


@dataclass
class CandidateEdge:
    """
    B-stage output: candidate edge between two claims.
    
    Generated by embedding similarity, adjacency, or keyword overlap.
    """
    src_id: str
    dst_id: str
    reason: Literal["sim", "adjacent", "keyword"]
    sim_score: float        # 0.0-1.0 (embeddings) or Jaccard (keywords)
    same_section: bool
    cross_topic: bool = False  # Edge crosses topic boundaries


@dataclass
class TypedEdge:
    """
    C-stage output: classified edge with relation and score.
    
    Only edges with relation != UNRELATED and score >= τ are kept.
    """
    src_id: str
    dst_id: str
    relation: EdgeRelation
    score: float            # 0.0-1.0 confidence
    rationale_short: str    # 10-25 words, logs only
    evidence_spans: str     # Key text supporting classification, ≤25 words
    cross_topic: bool = False  # Preserved from CandidateEdge
    same_section: bool = False  # Preserved from CandidateEdge (trace/explainability)

    def to_trace_dict(self) -> dict:
        """Convert to dict for tracing and explainability."""
        out: dict = {
            "src": self.src_id,
            "dst": self.dst_id,
            "rel": self.relation.value,
            "score": round(self.score, 2),
        }
        if self.rationale_short:
            out["rationale_short"] = self.rationale_short[:80]
        if self.evidence_spans:
            out["evidence_spans"] = self.evidence_spans[:80]
        if self.cross_topic:
            out["cross_topic"] = True
        if self.same_section:
            out["same_section"] = True
        return out
